export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_POST = "GET_POST";
export const GET_TARGET_POST = "GET_TARGET_POST";
export const GET_POST_COMMENT = "GET_POST_COMMENT";
export const POST_NEW_POST = "POST_NEW_POST";
export const POST_ADD_COMMENT = "POST_ADD_COMMENT";
